### ISSUE TITLE
Support for New SSR Changes in Angular 17

### ISSUE THREAD

**Issue by naveedahmed1** [MintPlayer/MintPlayer.AspNetCore.SpaServices#48]
Please add support for the new ssr changes in Angular 17 with vite and esbuild.

**Comment by naveedahmed1** [comment]
@PieterjanDeClippel what do you think about the support for server bundles generated through `@angular-devkit/build-angular:application`? Will it require major changes?

**Comment by PieterjanDeClippel** [comment]
Haven't tried using that until now [cref](https://www.npmjs.com/package/@angular-devkit/build-angular#builders)

**Comment by PieterjanDeClippel** [comment]
@naveedahmed1 Actually this repository only covers the .NET implementation and publishes those NuGet packages. Do you want to see the embedded demo project upgraded to 17? Or more?

**Comment by naveedahmed1** [comment]
Thanks @PieterjanDeClippel I am more interested in using the new builder in Angular 17 for SSR.

**Comment by PieterjanDeClippel** [comment]
Hi, I updated this repository to angular 17, and added a new section to the `angular.json` myself, the traditional way.

Sadly I think that the new builder is probably of no use to me. I have yet to test it out on my live environment, but I guess since I cannot send ajax calls to my api during SSR without crashing my application pool, it won't help me much.

If you manage to get it to work, you could omit all `OnSupplyData` stuff. Using the new `provideClientHydration()` angular will send the webrequest during ssr, and put the response in the `TransferState`, which prevents another webrequest from the browser. Personally I won't be using it any time soon myself because of a lack of time
